name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install deps
        run: go mod tidy

      - name: Build
        run: make build